spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coffeeshop #your db address
    username: root #your db username
    password: Hakuna21@ #your db password (if applicable)
    driver-class-name: com.mysql.cj.jdbc.Driver #your db driver (mysql, postgresql etc)
  thymeleaf:
    mode: HTML
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

  application:
    name: USER-SERVICE

  logging:
    level:
      org.thymeleaf: DEBUG
      org.thymeleaf.TemplateEngine: TRACE