spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coffeeshop
    username: root
    password: Hakuna21@
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

  application:
    name: USER-SERVICE

  logging:
    level:
      org.thymeleaf: DEBUG
      org.thymeleaf.TemplateEngine: TRACE